package DataDictionary.SQL.Generator;

/*Generated by MPS */

import jetbrains.mps.smodel.language.LanguageRuntime;
import jetbrains.mps.smodel.adapter.ids.SLanguageId;
import java.util.UUID;
import java.util.Collection;
import jetbrains.mps.generator.runtime.TemplateModule;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.smodel.runtime.ILanguageAspect;

public class Language extends LanguageRuntime {
  public static String MODULE_REF = "d212b829-e09d-4f3b-9710-f0eac8781c6d(DataDictionary.SQL.Generator)";
  public Language() {
  }
  @Override
  public String getNamespace() {
    return "DataDictionary.SQL.Generator";
  }

  @Override
  public int getVersion() {
    return 0;
  }

  public SLanguageId getId() {
    return new SLanguageId(UUID.fromString("d212b829-e09d-4f3b-9710-f0eac8781c6d"));
  }
  @Override
  protected String[] getExtendedLanguageIDs() {
    return new String[]{"DataDictionary"};
  }
  @Override
  public Collection<TemplateModule> getGenerators() {
    return TemplateUtil.<TemplateModule>asCollection(TemplateUtil.createInterpretedGenerator(this, "871d007d-a606-4ed1-9114-a95feb246814(DataDictionary.SQL.Generator#9076313498052755839)"));
  }
  @Override
  protected <T extends ILanguageAspect> T createAspect(Class<T> aspectClass) {
    return super.createAspect(aspectClass);
  }
}
