package DataDictionaryNew.Java;

/*Generated by MPS */


public class IspitnaPrijava {
  private String datumPrijave;
  private int ocena;
  private Student studentRef;
  private Predmet predmetRef;
  private Profesor profesorRef;

  public IspitnaPrijava() {
  }
  public void setDatumPrijave(String newValue) {
    datumPrijave = newValue;
  }
  public void setOcena(int newValue) {
    ocena = newValue;
  }
  public void setStudentRef(Student newValue) {
    studentRef = newValue;
  }
  public void setPredmetRef(Predmet newValue) {
    predmetRef = newValue;
  }
  public void setProfesorRef(Profesor newValue) {
    profesorRef = newValue;
  }
  public String getDatumPrijave() {
    return datumPrijave;
  }
  public int getOcena() {
    return ocena;
  }
  public Student getStudentRef() {
    return studentRef;
  }
  public Predmet getPredmetRef() {
    return predmetRef;
  }
  public Profesor getProfesorRef() {
    return profesorRef;
  }
}
