package DataDictionaryNew.Java;

/*Generated by MPS */


public class Mesto {
  private String naziv;
  private String ptt;

  public Mesto() {
  }
  public void setNaziv(String newValue) {
    naziv = newValue;
  }
  public void setPtt(String newValue) {
    ptt = newValue;
  }
  public String getNaziv() {
    return naziv;
  }
  public String getPtt() {
    return ptt;
  }
}
