package DataDictionaryNew.Java;

/*Generated by MPS */


public class Predmet {
  private String sifaPredmeta;
  private String nazivPredmeta;

  public Predmet() {
  }
  public void setSifaPredmeta(String newValue) {
    sifaPredmeta = newValue;
  }
  public void setNazivPredmeta(String newValue) {
    nazivPredmeta = newValue;
  }
  public String getSifaPredmeta() {
    return sifaPredmeta;
  }
  public String getNazivPredmeta() {
    return nazivPredmeta;
  }
}
