package DataDictionaryNew.Java;

/*Generated by MPS */


public class Profesor {
  private String imeProfesora;
  private String prezimeProfesora;

  public Profesor() {
  }
  public void setImeProfesora(String newValue) {
    imeProfesora = newValue;
  }
  public void setPrezimeProfesora(String newValue) {
    prezimeProfesora = newValue;
  }
  public String getImeProfesora() {
    return imeProfesora;
  }
  public String getPrezimeProfesora() {
    return prezimeProfesora;
  }
}
