package DataDictionaryNew.Java;

/*Generated by MPS */

import java.util.List;

public class Racun {
  private int brojRacuna;
  private String datum;
  private List<Stavka> stavkaList;

  public Racun() {
  }
  public void setBrojRacuna(int newValue) {
    brojRacuna = newValue;
  }
  public void setDatum(String newValue) {
    datum = newValue;
  }
  public void setStavkaList(List<Stavka> newValue) {
    stavkaList = newValue;
  }
  public int getBrojRacuna() {
    return brojRacuna;
  }
  public String getDatum() {
    return datum;
  }
  public List<Stavka> getStavkaList() {
    return stavkaList;
  }
}
