package DataDictionaryNew.Java;

/*Generated by MPS */


public class Stavka {
  private int redniBroj;
  private String proizvod;
  private int cena;
  private int kolicina;
  private Racun racunField;

  public Stavka() {
  }
  public void setRedniBroj(int newValue) {
    redniBroj = newValue;
  }
  public void setProizvod(String newValue) {
    proizvod = newValue;
  }
  public void setCena(int newValue) {
    cena = newValue;
  }
  public void setKolicina(int newValue) {
    kolicina = newValue;
  }
  public void setRacunField(Racun newValue) {
    racunField = newValue;
  }
  public int getRedniBroj() {
    return redniBroj;
  }
  public String getProizvod() {
    return proizvod;
  }
  public int getCena() {
    return cena;
  }
  public int getKolicina() {
    return kolicina;
  }
  public Racun getRacunField() {
    return racunField;
  }
}
