package DataDictionaryNew.Java;

/*Generated by MPS */


public class Student {
  private String imeStudenta;
  private String prezimeStudenta;
  private int brojIndeksa;

  public Student() {
  }
  public void setImeStudenta(String newValue) {
    imeStudenta = newValue;
  }
  public void setPrezimeStudenta(String newValue) {
    prezimeStudenta = newValue;
  }
  public void setBrojIndeksa(int newValue) {
    brojIndeksa = newValue;
  }
  public String getImeStudenta() {
    return imeStudenta;
  }
  public String getPrezimeStudenta() {
    return prezimeStudenta;
  }
  public int getBrojIndeksa() {
    return brojIndeksa;
  }
}
