package DataDictionaryNew.sandbox;

/*Generated by MPS */


public class Adresa {
  private String ulica;
  private String kucniBroj;
  public Adresa() {
  }
  public void setUlica(String newValue) {
    ulica = newValue;
  }
  public void setKucniBroj(String newValue) {
    kucniBroj = newValue;
  }
  public String getUlica() {
    return ulica;
  }
  public String getKucniBroj() {
    return kucniBroj;
  }
}
