package DataDictionaryNew.sandbox;

/*Generated by MPS */


public class Mesto {
  private int mestoId;
  private String nazivMesta;
  public Mesto() {
  }
  public void setMestoId(int newValue) {
    mestoId = newValue;
  }
  public void setNazivMesta(String newValue) {
    nazivMesta = newValue;
  }
  public int getMestoId() {
    return mestoId;
  }
  public String getNazivMesta() {
    return nazivMesta;
  }
}
