package DataDictionaryNew.sandbox;

/*Generated by MPS */

import java.util.List;

public class Ucenik {
  private String ime;
  private String prezime;
  private int godine;
  private Mesto mestoField;
  private Adresa adresaRef;
  private List<Mesto> mestoList;
  private Adresa adresaField;
  public Ucenik() {
  }
  public void setIme(String newValue) {
    ime = newValue;
  }
  public void setPrezime(String newValue) {
    prezime = newValue;
  }
  public void setGodine(int newValue) {
    godine = newValue;
  }
  public void setMestoField(Mesto newValue) {
    mestoField = newValue;
  }
  public void setAdresaRef(Adresa newValue) {
    adresaRef = newValue;
  }
  public void setMestoList(List<Mesto> newValue) {
    mestoList = newValue;
  }
  public void setAdresaField(Adresa newValue) {
    adresaField = newValue;
  }
  public String getIme() {
    return ime;
  }
  public String getPrezime() {
    return prezime;
  }
  public int getGodine() {
    return godine;
  }
  public Mesto getMestoField() {
    return mestoField;
  }
  public Adresa getAdresaRef() {
    return adresaRef;
  }
  public List<Mesto> getMestoList() {
    return mestoList;
  }
  public Adresa getAdresaField() {
    return adresaField;
  }
}
