package DataDictionaryNew.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Collections;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6d0936L, "DataDictionaryNew.structure.Aggregation"))) {
        return Collections.<ConceptEditor>singletonList(new Aggregation_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5c982cbd675b3b19L, "DataDictionaryNew.structure.AggregationAsAField"))) {
        return Collections.<ConceptEditor>singletonList(new AggregationAsAField_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6d0933L, "DataDictionaryNew.structure.DataDictionary"))) {
        return Collections.<ConceptEditor>singletonList(new DataDictionary_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6e8d6cL, "DataDictionaryNew.structure.Definitions"))) {
        return Collections.<ConceptEditor>singletonList(new Definitions_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af76826bL, "DataDictionaryNew.structure.ExclusiveSpecializationAsField"))) {
        return Collections.<ConceptEditor>singletonList(new ExclusiveSpecializationAsField_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6dcd98L, "DataDictionaryNew.structure.Field"))) {
        return Collections.<ConceptEditor>singletonList(new Field_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6dcd9bL, "DataDictionaryNew.structure.FieldDefinition"))) {
        return Collections.<ConceptEditor>singletonList(new FieldDefinition_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af7681e7L, "DataDictionaryNew.structure.FieldRef"))) {
        return Collections.<ConceptEditor>singletonList(new FieldRef_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af7682beL, "DataDictionaryNew.structure.NonExclusiveSpecializationAsField"))) {
        return Collections.<ConceptEditor>singletonList(new NonExclusiveSpecializationAsField_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x4709666cc5e0197fL, "DataDictionaryNew.structure.PredefinedDomain"))) {
        return Collections.<ConceptEditor>singletonList(new PredefinedDomain_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x4709666cc5e01970L, "DataDictionaryNew.structure.Restriction"))) {
        return Collections.<ConceptEditor>singletonList(new Restriction_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af7681e1L, "DataDictionaryNew.structure.SetOfComponentsAsAField"))) {
        return Collections.<ConceptEditor>singletonList(new SetOfComponentsAsAField_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x3e70a0b137744c3bL, "DataDictionaryNew.structure.SetStructureRef"))) {
        return Collections.<ConceptEditor>singletonList(new SetStructureRef_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x4709666cc5e01982L, "DataDictionaryNew.structure.UserDefinedDomain"))) {
        return Collections.<ConceptEditor>singletonList(new UserDefinedDomain_Editor());
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }



}
