package DatDictonary.Java;

/*Generated by MPS */

import jetbrains.mps.smodel.language.LanguageRuntime;
import jetbrains.mps.smodel.adapter.ids.SLanguageId;
import java.util.UUID;
import java.util.Collection;
import jetbrains.mps.generator.runtime.TemplateModule;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.smodel.runtime.ILanguageAspect;
import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;

public class Language extends LanguageRuntime {
  public static String MODULE_REF = "d9ed2390-ed93-4112-a500-557becc66fa7(DatDictonary.Java)";
  public Language() {
  }
  @Override
  public String getNamespace() {
    return "DatDictonary.Java";
  }

  @Override
  public int getVersion() {
    return 0;
  }

  public SLanguageId getId() {
    return new SLanguageId(UUID.fromString("d9ed2390-ed93-4112-a500-557becc66fa7"));
  }
  @Override
  protected String[] getExtendedLanguageIDs() {
    return new String[]{};
  }
  @Override
  public Collection<TemplateModule> getGenerators() {
    return TemplateUtil.<TemplateModule>asCollection(TemplateUtil.createInterpretedGenerator(this, "f3a2a736-5921-4069-b05c-971f1beec1ce(DatDictonary.Java#7010553778802364139)"));
  }
  @Override
  protected <T extends ILanguageAspect> T createAspect(Class<T> aspectClass) {
    if (aspectClass == EditorAspectDescriptor.class) {
      return ((T) new EditorAspectDescriptorBase());
    }
    return super.createAspect(aspectClass);
  }
}
