package DataDictonary.SQL.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum DateFormt {
  DD_MM_YYYY("DD-MM-YYYY", "DD-MM-YYYY"),
  YYYY_MM_DD("YYYY-MM-DD", "YYYY-MM-DD"),
  MM_DD_YYYY("MM-DD-YYYY", "MM-DD-YYYY");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private DateFormt(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<DateFormt> getConstants() {
    List<DateFormt> list = ListSequence.fromList(new LinkedList<DateFormt>());
    ListSequence.fromList(list).addElement(DateFormt.DD_MM_YYYY);
    ListSequence.fromList(list).addElement(DateFormt.YYYY_MM_DD);
    ListSequence.fromList(list).addElement(DateFormt.MM_DD_YYYY);
    return list;
  }
  public static DateFormt getDefault() {
    return DateFormt.YYYY_MM_DD;
  }
  public static DateFormt parseValue(String value) {
    if (value == null) {
      return DateFormt.getDefault();
    }
    if (value.equals(DateFormt.DD_MM_YYYY.getValueAsString())) {
      return DateFormt.DD_MM_YYYY;
    }
    if (value.equals(DateFormt.YYYY_MM_DD.getValueAsString())) {
      return DateFormt.YYYY_MM_DD;
    }
    if (value.equals(DateFormt.MM_DD_YYYY.getValueAsString())) {
      return DateFormt.MM_DD_YYYY;
    }
    return DateFormt.getDefault();
  }
}
