package DataDictonary.SQL.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum Rule {
  SetNull("SetNull ", "SetNull"),
  Restriction("Restriction", "Restriction"),
  Cascade("Cascade", "Cascade"),
  Default("Defult", "Default");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private Rule(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<Rule> getConstants() {
    List<Rule> list = ListSequence.fromList(new LinkedList<Rule>());
    ListSequence.fromList(list).addElement(Rule.SetNull);
    ListSequence.fromList(list).addElement(Rule.Restriction);
    ListSequence.fromList(list).addElement(Rule.Cascade);
    ListSequence.fromList(list).addElement(Rule.Default);
    return list;
  }
  public static Rule getDefault() {
    return Rule.SetNull;
  }
  public static Rule parseValue(String value) {
    if (value == null) {
      return Rule.getDefault();
    }
    if (value.equals(Rule.SetNull.getValueAsString())) {
      return Rule.SetNull;
    }
    if (value.equals(Rule.Restriction.getValueAsString())) {
      return Rule.Restriction;
    }
    if (value.equals(Rule.Cascade.getValueAsString())) {
      return Rule.Cascade;
    }
    if (value.equals(Rule.Default.getValueAsString())) {
      return Rule.Default;
    }
    return Rule.getDefault();
  }
}
