package DataDictionaryNew.Java2;

/*Generated by MPS */


public class Mesto {
  private String naziv;
  private int ptt;

  public Mesto() {
  }
  public void setNaziv(String newValue) {
    naziv = newValue;
  }
  public void setPtt(int newValue) {
    ptt = newValue;
  }
  public String getNaziv() {
    return naziv;
  }
  public int getPtt() {
    return ptt;
  }
}
