package DataDictionaryNew.Java2;

/*Generated by MPS */


public class Nadmetanje {
  private int rb;
  private String oznaka;
  private int pocetnaCena;
  private int depozit;
  private int povrsina;
  private Oglas oglasField;

  public Nadmetanje() {
  }
  public void setRb(int newValue) {
    rb = newValue;
  }
  public void setOznaka(String newValue) {
    oznaka = newValue;
  }
  public void setPocetnaCena(int newValue) {
    pocetnaCena = newValue;
  }
  public void setDepozit(int newValue) {
    depozit = newValue;
  }
  public void setPovrsina(int newValue) {
    povrsina = newValue;
  }
  public void setOglasField(Oglas newValue) {
    oglasField = newValue;
  }
  public int getRb() {
    return rb;
  }
  public String getOznaka() {
    return oznaka;
  }
  public int getPocetnaCena() {
    return pocetnaCena;
  }
  public int getDepozit() {
    return depozit;
  }
  public int getPovrsina() {
    return povrsina;
  }
  public Oglas getOglasField() {
    return oglasField;
  }
}
