package DataDictionaryNew.Java2;

/*Generated by MPS */

import java.util.List;

public class Oglas {
  private String nazivOpstine;
  private String zaGodinu;
  private int licitacioniKorak;
  private int maxPovZakupa;
  private List<Nadmetanje> nadmetanjeList;

  public Oglas() {
  }
  public void setNazivOpstine(String newValue) {
    nazivOpstine = newValue;
  }
  public void setZaGodinu(String newValue) {
    zaGodinu = newValue;
  }
  public void setLicitacioniKorak(int newValue) {
    licitacioniKorak = newValue;
  }
  public void setMaxPovZakupa(int newValue) {
    maxPovZakupa = newValue;
  }
  public void setNadmetanjeList(List<Nadmetanje> newValue) {
    nadmetanjeList = newValue;
  }
  public String getNazivOpstine() {
    return nazivOpstine;
  }
  public String getZaGodinu() {
    return zaGodinu;
  }
  public int getLicitacioniKorak() {
    return licitacioniKorak;
  }
  public int getMaxPovZakupa() {
    return maxPovZakupa;
  }
  public List<Nadmetanje> getNadmetanjeList() {
    return nadmetanjeList;
  }
}
