package DataDictionaryNew.Java2;

/*Generated by MPS */


public class PonudjacPravno {
  private int mb;
  private String naziv;

  public PonudjacPravno() {
  }
  public void setMb(int newValue) {
    mb = newValue;
  }
  public void setNaziv(String newValue) {
    naziv = newValue;
  }
  public int getMb() {
    return mb;
  }
  public String getNaziv() {
    return naziv;
  }
}
