package DataDictionaryNew.Java2;

/*Generated by MPS */


public class PonudjacFizicko {
  private int jmbg;
  private String ime;
  private String imeRoditelja;
  private String prezine;

  public PonudjacFizicko() {
  }
  public void setJmbg(int newValue) {
    jmbg = newValue;
  }
  public void setIme(String newValue) {
    ime = newValue;
  }
  public void setImeRoditelja(String newValue) {
    imeRoditelja = newValue;
  }
  public void setPrezine(String newValue) {
    prezine = newValue;
  }
  public int getJmbg() {
    return jmbg;
  }
  public String getIme() {
    return ime;
  }
  public String getImeRoditelja() {
    return imeRoditelja;
  }
  public String getPrezine() {
    return prezine;
  }
}
