package DataDictionaryNew.Java2;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public class Ponudjac {
  private String emali;
  private String telefon;
  private Mesto mestoField;
  private PonudjacFizicko ponudjacFizickoField;
  private PonudjacPravno ponudjacPravnoField;
  private List<Object> inLineRef = ListSequence.fromList(new LinkedList<Object>());

  public Ponudjac() {
  }
  public void setEmali(String newValue) {
    emali = newValue;
  }
  public void setTelefon(String newValue) {
    telefon = newValue;
  }
  public void setMestoField(Mesto newValue) {
    mestoField = newValue;
  }
  public void setPonudjacFizickoField(PonudjacFizicko newValue) {
    if (isInLineRefEmpty()) {
      ponudjacFizickoField = newValue;
    }
  }
  public void setPonudjacPravnoField(PonudjacPravno newValue) {
    if (isInLineRefEmpty()) {
      ponudjacPravnoField = newValue;
    }
  }
  public String getEmali() {
    return emali;
  }
  public String getTelefon() {
    return telefon;
  }
  public Mesto getMestoField() {
    return mestoField;
  }
  public PonudjacFizicko getPonudjacFizickoField() {
    return ponudjacFizickoField;
  }
  public PonudjacPravno getPonudjacPravnoField() {
    return ponudjacPravnoField;
  }
  private void inLineRef() {
    ListSequence.fromList(inLineRef).addElement(ponudjacFizickoField);
    ListSequence.fromList(inLineRef).addElement(ponudjacPravnoField);
  }
  private boolean isInLineRefEmpty() {
    for (Object item : inLineRef) {
      if (item != null) {
        return false;
      }
    }
    return true;
  }
}
