package DataDictionaryNew.Java2;

/*Generated by MPS */


public class PrijavaPravno {
  private boolean izvodIzPrivrednogReg;
  private PonudjacPravno ponudjacPravnoField;

  public PrijavaPravno() {
  }
  public void setIzvodIzPrivrednogReg(boolean newValue) {
    izvodIzPrivrednogReg = newValue;
  }
  public void setPonudjacPravnoField(PonudjacPravno newValue) {
    ponudjacPravnoField = newValue;
  }
  public boolean getIzvodIzPrivrednogReg() {
    return izvodIzPrivrednogReg;
  }
  public PonudjacPravno getPonudjacPravnoField() {
    return ponudjacPravnoField;
  }
}
