package DataDictionaryNew.Java2;

/*Generated by MPS */


public class PrijavaFizicko {
  private boolean licnaKarta;
  private boolean dokazOgranicnomZemljistu;
  private PonudjacFizicko ponudjacFizickoField;

  public PrijavaFizicko() {
  }
  public void setLicnaKarta(boolean newValue) {
    licnaKarta = newValue;
  }
  public void setDokazOgranicnomZemljistu(boolean newValue) {
    dokazOgranicnomZemljistu = newValue;
  }
  public void setPonudjacFizickoField(PonudjacFizicko newValue) {
    ponudjacFizickoField = newValue;
  }
  public boolean getLicnaKarta() {
    return licnaKarta;
  }
  public boolean getDokazOgranicnomZemljistu() {
    return dokazOgranicnomZemljistu;
  }
  public PonudjacFizicko getPonudjacFizickoField() {
    return ponudjacFizickoField;
  }
}
