package DataDictionary.SQL.Generator.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.generator.template.MappingScriptContext;
import java.util.List;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import java.util.Iterator;
import jetbrains.mps.baseLanguage.closures.runtime.Wrappers;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;

@Generated
public class QueriesGenerated {
  public static boolean baseMappingRule_Condition_9072010249895890776(final BaseMappingRuleContext _context) {
    {
      final SNode aggregationAsAField = _context.getNode();
      if (SNodeOperations.isInstanceOf(aggregationAsAField, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5c982cbd675b3b19L, "DataDictionary.structure.AggregationAsAField"))) {
        return true;
      }
    }
    return false;
  }
  public static boolean baseMappingRule_Condition_9072010249896263527(final BaseMappingRuleContext _context) {
    {
      final SNode field = _context.getNode();
      if (SNodeOperations.isInstanceOf(field, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b238f7L, "DataDictionary.structure.FieldStructure"))) {
        return true;
      }
    }
    return false;
  }
  public static Object propertyMacro_GetPropertyValue_3004211968619054467(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x59470266038a5a4eL, 0x59470266038a5a4fL, "length"));
  }
  public static Object propertyMacro_GetPropertyValue_9072010249896380095(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + "Id";
  }
  public static Object propertyMacro_GetPropertyValue_3004211968618337487(final PropertyMacroContext _context) {
    {
      final SNode fieldDefinition = _context.getNode();
      if (SNodeOperations.isInstanceOf(fieldDefinition, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6dcd9bL, "DataDictionary.structure.FieldDefinition"))) {
        return SPropertyOperations.getString(SLinkOperations.getTarget(fieldDefinition, MetaAdapterFactory.getReferenceLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6dcd9bL, 0x62cd8899af6e57beL, "field")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
      }
    }
    return "";
  }
  public static Object propertyMacro_GetPropertyValue_9072010249896869249(final PropertyMacroContext _context) {
    {
      final SNode aggregationAsAField = _context.getNode();
      if (SNodeOperations.isInstanceOf(aggregationAsAField, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5c982cbd675b3b19L, "DataDictionary.structure.AggregationAsAField"))) {
        return SPropertyOperations.getString(SLinkOperations.getTarget(aggregationAsAField, MetaAdapterFactory.getReferenceLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af79708bL, 0x62cd8899af797090L, "strucutreRef")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + "Id";
      }
    }
    {
      final SNode fieldStructure = _context.getNode();
      if (SNodeOperations.isInstanceOf(fieldStructure, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b238f7L, "DataDictionary.structure.FieldStructure"))) {
        return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(fieldStructure, MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b238f7L, 0x5947026603b9a40eL, "structure")), MetaAdapterFactory.getReferenceLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b9a3f8L, 0x5947026603b9a3f9L, "structureRef")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + "Id";
      }
    }
    return "";
  }
  public static Object propertyMacro_GetPropertyValue_3004211968618346495(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_9072010249896349635(final PropertyMacroContext _context) {
    return "PK_" + SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_9072010249896630665(final PropertyMacroContext _context) {
    {
      final SNode aggregationAsAField = _context.getNode();
      if (SNodeOperations.isInstanceOf(aggregationAsAField, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5c982cbd675b3b19L, "DataDictionary.structure.AggregationAsAField"))) {
        return "FK_" + SPropertyOperations.getString(SNodeOperations.getNodeAncestor(aggregationAsAField, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6d0936L, "DataDictionary.structure.Aggregation"), false, false), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + "_" + SPropertyOperations.getString(SLinkOperations.getTarget(aggregationAsAField, MetaAdapterFactory.getReferenceLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af79708bL, 0x62cd8899af797090L, "strucutreRef")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
      }
    }
    {
      final SNode fieldStructure = _context.getNode();
      if (SNodeOperations.isInstanceOf(fieldStructure, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b238f7L, "DataDictionary.structure.FieldStructure"))) {
        return "FK_" + SPropertyOperations.getString(SNodeOperations.getNodeAncestor(fieldStructure, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6d0936L, "DataDictionary.structure.Aggregation"), false, false), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + "_" + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(fieldStructure, MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b238f7L, 0x5947026603b9a40eL, "structure")), MetaAdapterFactory.getReferenceLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b9a3f8L, 0x5947026603b9a3f9L, "structureRef")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
      }
    }
    return "";
  }
  public static Object propertyMacro_GetPropertyValue_4511370387742614664(final PropertyMacroContext _context) {
    {
      final SNode aggregationAsAField = _context.getNode();
      if (SNodeOperations.isInstanceOf(aggregationAsAField, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5c982cbd675b3b19L, "DataDictionary.structure.AggregationAsAField"))) {
        return "FK_" + SPropertyOperations.getString(SNodeOperations.getNodeAncestor(aggregationAsAField, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6d0936L, "DataDictionary.structure.Aggregation"), false, false), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + "_" + SPropertyOperations.getString(SLinkOperations.getTarget(aggregationAsAField, MetaAdapterFactory.getReferenceLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af79708bL, 0x62cd8899af797090L, "strucutreRef")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
      }
    }
    {
      final SNode fieldStructure = _context.getNode();
      if (SNodeOperations.isInstanceOf(fieldStructure, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b238f7L, "DataDictionary.structure.FieldStructure"))) {
        return "FK_" + SPropertyOperations.getString(SNodeOperations.getNodeAncestor(fieldStructure, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6d0936L, "DataDictionary.structure.Aggregation"), false, false), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + "_" + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(fieldStructure, MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b238f7L, 0x5947026603b9a40eL, "structure")), MetaAdapterFactory.getReferenceLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b9a3f8L, 0x5947026603b9a3f9L, "structureRef")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
      }
    }
    return "";
  }
  public static Object propertyMacro_GetPropertyValue_4511370387742930337(final PropertyMacroContext _context) {
    String value = new String();

    for (SNode item : ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603af5e83L, 0x5947026603af5eb5L, "fields")))) {
      {
        final SNode aggregationAsAField = item;
        if (SNodeOperations.isInstanceOf(aggregationAsAField, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5c982cbd675b3b19L, "DataDictionary.structure.AggregationAsAField"))) {
          value = value + SPropertyOperations.getString(SLinkOperations.getTarget(aggregationAsAField, MetaAdapterFactory.getReferenceLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af79708bL, 0x62cd8899af797090L, "strucutreRef")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + "Id" + " IS NOT NULL OR ";
        }
      }
      {
        final SNode fieldStructure = item;
        if (SNodeOperations.isInstanceOf(fieldStructure, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b238f7L, "DataDictionary.structure.FieldStructure"))) {
          value = value + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(fieldStructure, MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b238f7L, 0x5947026603b9a40eL, "structure")), MetaAdapterFactory.getReferenceLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b9a3f8L, 0x5947026603b9a3f9L, "structureRef")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + "Id" + " IS NOT NULL OR ";
        }
      }
    }

    if (value.length() > 0) {
      value = value.substring(0, value.length() - 4);
    }
    return value;
  }
  public static Object propertyMacro_GetPropertyValue_4511370387743726646(final PropertyMacroContext _context) {
    return "CK_" + SPropertyOperations.getString(SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6d0936L, "DataDictionary.structure.Aggregation"), false, false), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_4511370387742446708(final PropertyMacroContext _context) {
    {
      final SNode aggregationAsAField = _context.getNode();
      if (SNodeOperations.isInstanceOf(aggregationAsAField, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5c982cbd675b3b19L, "DataDictionary.structure.AggregationAsAField"))) {
        return SPropertyOperations.getString(SLinkOperations.getTarget(aggregationAsAField, MetaAdapterFactory.getReferenceLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af79708bL, 0x62cd8899af797090L, "strucutreRef")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + "Id";
      }
    }
    {
      final SNode fieldStructure = _context.getNode();
      if (SNodeOperations.isInstanceOf(fieldStructure, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b238f7L, "DataDictionary.structure.FieldStructure"))) {
        return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(fieldStructure, MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b238f7L, 0x5947026603b9a40eL, "structure")), MetaAdapterFactory.getReferenceLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b9a3f8L, 0x5947026603b9a3f9L, "structureRef")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + "Id";
      }
    }
    return "";
  }
  public static Object propertyMacro_GetPropertyValue_9076313498053640791(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_9072010249895897086(final PropertyMacroContext _context) {
    {
      final SNode aggregationAsAField = _context.getNode();
      if (SNodeOperations.isInstanceOf(aggregationAsAField, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5c982cbd675b3b19L, "DataDictionary.structure.AggregationAsAField"))) {
        return "FK_" + SPropertyOperations.getString(SLinkOperations.getTarget(aggregationAsAField, MetaAdapterFactory.getReferenceLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af79708bL, 0x62cd8899af797090L, "strucutreRef")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
      }
    }
    {
      final SNode fieldStructure = _context.getNode();
      if (SNodeOperations.isInstanceOf(fieldStructure, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b238f7L, "DataDictionary.structure.FieldStructure"))) {
        return "FK_" + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(fieldStructure, MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b238f7L, 0x5947026603b9a40eL, "structure")), MetaAdapterFactory.getReferenceLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b9a3f8L, 0x5947026603b9a3f9L, "structureRef")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
      }
    }
    return "";
  }
  public static boolean ifMacro_Condition_3004211968618341098(final IfMacroContext _context) {
    {
      final SNode aggregation = _context.getNode();
      if (SNodeOperations.isInstanceOf(aggregation, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6d0936L, "DataDictionary.structure.Aggregation"))) {
        return true;
      }
    }
    return false;
  }
  public static SNode sourceNodeQuery_3004211968619087616(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6dcd9bL, 0x62cd8899af6e57b8L, "domen"));
  }
  public static SNode sourceNodeQuery_9072010249896864304(final SourceSubstituteMacroNodeContext _context) {
    {
      final SNode aggregationAsAField = _context.getNode();
      if (SNodeOperations.isInstanceOf(aggregationAsAField, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5c982cbd675b3b19L, "DataDictionary.structure.AggregationAsAField"))) {
        return aggregationAsAField;
      }
    }
    {
      final SNode fieldStructure = _context.getNode();
      if (SNodeOperations.isInstanceOf(fieldStructure, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b238f7L, "DataDictionary.structure.FieldStructure"))) {
        return fieldStructure;
      }
    }
    return null;
  }
  public static SNode sourceNodeQuery_9072010249896623977(final SourceSubstituteMacroNodeContext _context) {
    {
      final SNode aggregationAsAField = _context.getNode();
      if (SNodeOperations.isInstanceOf(aggregationAsAField, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5c982cbd675b3b19L, "DataDictionary.structure.AggregationAsAField"))) {
        return aggregationAsAField;
      }
    }
    {
      final SNode fieldStructure = _context.getNode();
      if (SNodeOperations.isInstanceOf(fieldStructure, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b238f7L, "DataDictionary.structure.FieldStructure"))) {
        return fieldStructure;
      }
    }
    return null;
  }
  public static SNode sourceNodeQuery_4511370387742610877(final SourceSubstituteMacroNodeContext _context) {
    {
      final SNode inLine = _context.getNode();
      if (SNodeOperations.isInstanceOf(inLine, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603af5eb4L, "DataDictionary.structure.ExclusiveSpecializationInLine"))) {
        return inLine;
      }
    }
    return null;
  }
  public static SNode sourceNodeQuery_4511370387742925031(final SourceSubstituteMacroNodeContext _context) {
    {
      final SNode inLine = _context.getNode();
      if (SNodeOperations.isInstanceOf(inLine, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603af5eb4L, "DataDictionary.structure.ExclusiveSpecializationInLine"))) {
        return inLine;
      }
    }
    return null;
  }
  public static SNode sourceNodeQuery_4511370387742101591(final SourceSubstituteMacroNodeContext _context) {
    {
      final SNode inLine = _context.getNode();
      if (SNodeOperations.isInstanceOf(inLine, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603af5eb4L, "DataDictionary.structure.ExclusiveSpecializationInLine"))) {
        return inLine;
      }
    }
    return null;
  }
  public static SNode sourceNodeQuery_4511370387742850944(final SourceSubstituteMacroNodeContext _context) {
    {
      final SNode inLine = _context.getNode();
      if (SNodeOperations.isInstanceOf(inLine, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603af5eb4L, "DataDictionary.structure.ExclusiveSpecializationInLine"))) {
        return inLine;
      }
    }
    return null;
  }
  public static Iterable<SNode> sourceNodesQuery_3004211968618345386(final SourceSubstituteMacroNodesContext _context) {
    {
      final SNode aggregation = _context.getNode();
      if (SNodeOperations.isInstanceOf(aggregation, MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6d0936L, "DataDictionary.structure.Aggregation"))) {
        return SLinkOperations.getChildren(SLinkOperations.getTarget(aggregation, MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x64e4581da5cc8045L, 0x62cd8899af6e8d74L, "definitionForFields")), MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6e8d6cL, 0x62cd8899af6e8d6dL, "fieldDefinitionList"));
      }
    }
    return null;
  }
  public static Iterable<SNode> sourceNodesQuery_9072010249896842102(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x64e4581da5cc8045L, 0x62cd8899af6e8d72L, "fieldList"));
  }
  public static Iterable<SNode> sourceNodesQuery_3004211968618334603(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6d0933L, 0x62cd8899af6d0939L, "structures"));
  }
  public static Iterable<SNode> sourceNodesQuery_9072010249896614869(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x64e4581da5cc8045L, 0x62cd8899af6e8d72L, "fieldList"));
  }
  public static Iterable<SNode> sourceNodesQuery_4511370387742602308(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x64e4581da5cc8045L, 0x62cd8899af6e8d72L, "fieldList"));
  }
  public static Iterable<SNode> sourceNodesQuery_4511370387742729658(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603af5e83L, 0x5947026603af5eb5L, "fields"));
  }
  public static Iterable<SNode> sourceNodesQuery_4511370387742915243(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x64e4581da5cc8045L, 0x62cd8899af6e8d72L, "fieldList"));
  }
  public static Iterable<SNode> sourceNodesQuery_4511370387742087082(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x64e4581da5cc8045L, 0x62cd8899af6e8d72L, "fieldList"));
  }
  public static Iterable<SNode> sourceNodesQuery_4511370387742272670(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603af5e83L, 0x5947026603af5eb5L, "fields"));
  }
  public static void mappingScript_CodeBlock_6597202854629355590(final MappingScriptContext _context) {
    List<SNode> foreingKeys = SModelOperations.nodes(_context.getModel(), MetaAdapterFactory.getConcept(0x1e512a67eb48409aL, 0x8f1d3b3721b063dfL, 0x7df58b09c184669dL, "DataDictonary.SQL.structure.ForeignKey"));
    for (final SNode fkey : ListSequence.fromList(foreingKeys)) {
      // key ref 
      SLinkOperations.setTarget(SLinkOperations.addNewChild(fkey, MetaAdapterFactory.getContainmentLink(0x1e512a67eb48409aL, 0x8f1d3b3721b063dfL, 0x7df58b09c1846695L, 0x7df58b09c18481cbL, "keysRef"), MetaAdapterFactory.getConcept(0x1e512a67eb48409aL, 0x8f1d3b3721b063dfL, 0x7df58b09c18481c8L, "DataDictonary.SQL.structure.KeysRef")), MetaAdapterFactory.getReferenceLink(0x1e512a67eb48409aL, 0x8f1d3b3721b063dfL, 0x7df58b09c18481c8L, 0x7df58b09c18481c9L, "attribute"), ListSequence.fromList(SLinkOperations.getChildren(SNodeOperations.getNodeAncestor(fkey, MetaAdapterFactory.getConcept(0x1e512a67eb48409aL, 0x8f1d3b3721b063dfL, 0x7df58b09c1846681L, "DataDictonary.SQL.structure.BaseRelation"), false, false), MetaAdapterFactory.getContainmentLink(0x1e512a67eb48409aL, 0x8f1d3b3721b063dfL, 0x7df58b09c1846681L, 0x7df58b09c1846685L, "atributes"))).findFirst(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals(SPropertyOperations.getString(fkey, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).substring(SPropertyOperations.getString(fkey, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).lastIndexOf("_") + 1) + "Id");
        }
      }));

      // foreign key BaseRelation 
      SLinkOperations.setTarget(fkey, MetaAdapterFactory.getReferenceLink(0x1e512a67eb48409aL, 0x8f1d3b3721b063dfL, 0x7df58b09c184669dL, 0x7df58b09c18466a2L, "baseRelation"), ListSequence.fromList(SModelOperations.nodes(_context.getModel(), MetaAdapterFactory.getConcept(0x1e512a67eb48409aL, 0x8f1d3b3721b063dfL, 0x7df58b09c1846681L, "DataDictonary.SQL.structure.BaseRelation"))).findFirst(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals(SPropertyOperations.getString(fkey, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).substring(SPropertyOperations.getString(fkey, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).lastIndexOf("_") + 1));
        }
      }));

      // foreign key BaseRelation attribute 
      SNode fKeyBaseRelation = ListSequence.fromList(SModelOperations.nodes(_context.getModel(), MetaAdapterFactory.getConcept(0x1e512a67eb48409aL, 0x8f1d3b3721b063dfL, 0x7df58b09c1846681L, "DataDictonary.SQL.structure.BaseRelation"))).findFirst(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals(SPropertyOperations.getString(fkey, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).substring(SPropertyOperations.getString(fkey, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).lastIndexOf("_") + 1));
        }
      });

      SLinkOperations.setTarget(SLinkOperations.addNewChild(fkey, MetaAdapterFactory.getContainmentLink(0x1e512a67eb48409aL, 0x8f1d3b3721b063dfL, 0x7df58b09c184669dL, 0x7df58b09c18adcb8L, "foreignKeyRef"), MetaAdapterFactory.getConcept(0x1e512a67eb48409aL, 0x8f1d3b3721b063dfL, 0x7df58b09c18481cdL, "DataDictonary.SQL.structure.ForeignKeysRef")), MetaAdapterFactory.getReferenceLink(0x1e512a67eb48409aL, 0x8f1d3b3721b063dfL, 0x7df58b09c18481cdL, 0x7df58b09c1885b5dL, "attribute"), ListSequence.fromList(SLinkOperations.getChildren(fKeyBaseRelation, MetaAdapterFactory.getContainmentLink(0x1e512a67eb48409aL, 0x8f1d3b3721b063dfL, 0x7df58b09c1846681L, 0x7df58b09c1846685L, "atributes"))).findFirst(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals(SPropertyOperations.getString(fkey, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).substring(SPropertyOperations.getString(fkey, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).lastIndexOf("_") + 1) + "Id");
        }
      }));
    }
  }
  public static void mappingScript_CodeBlock_6597202854632113206(final MappingScriptContext _context) {
    List<SNode> setOfComponentsAsAFields = SModelOperations.nodes(_context.getModel(), MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af7681e1L, "DataDictionary.structure.SetOfComponentsAsAField"));

    {
      Iterator<SNode> componentField_it = ListSequence.fromList(setOfComponentsAsAFields).iterator();
      final Wrappers._T<SNode> componentField_var = new Wrappers._T<SNode>();
      while (componentField_it.hasNext()) {
        componentField_var.value = componentField_it.next();

        SNode slabObjekat = ListSequence.fromList(SModelOperations.nodes(_context.getModel(), MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6d0936L, "DataDictionary.structure.Aggregation"))).findFirst(new IWhereFilter<SNode>() {
          public boolean accept(SNode it) {
            return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals(SPropertyOperations.getString(SLinkOperations.getTarget(componentField_var.value, MetaAdapterFactory.getReferenceLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af79708bL, 0x62cd8899af797090L, "strucutreRef")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
          }
        });

        SNode jakObjekat = ListSequence.fromList(SModelOperations.nodes(_context.getModel(), MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x62cd8899af6d0936L, "DataDictionary.structure.Aggregation"))).findFirst(new IWhereFilter<SNode>() {
          public boolean accept(SNode it) {
            return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals(SPropertyOperations.getString(SNodeOperations.getNodeAncestor(componentField_var.value, MetaAdapterFactory.getInterfaceConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x64e4581da5cc8045L, "DataDictionary.structure.Structure"), false, false), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
          }
        });

        SNode fieldStructure = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b238f7L, "DataDictionary.structure.FieldStructure"));
        SNode structureRef = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b9a3f8L, "DataDictionary.structure.StructureRef"));
        SLinkOperations.setTarget(structureRef, MetaAdapterFactory.getReferenceLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b9a3f8L, 0x5947026603b9a3f9L, "structureRef"), jakObjekat);
        SLinkOperations.setTarget(fieldStructure, MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x5947026603b238f7L, 0x5947026603b9a40eL, "structure"), structureRef);

        ListSequence.fromList(SLinkOperations.getChildren(slabObjekat, MetaAdapterFactory.getContainmentLink(0xe00ab26049b415aL, 0x83b6dc09f3615dc4L, 0x64e4581da5cc8045L, 0x62cd8899af6e8d72L, "fieldList"))).addElement(fieldStructure);
      }
    }

  }
}
