package DataDictionaryNew.behavior;

/*Generated by MPS */


/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public abstract class StructureAsAField_BehaviorDescriptor extends AbstractField_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "DataDictionaryNew.structure.StructureAsAField";
  }

}
